# This is a basic workflow to help you get started with Actions

name: Deployment of Website to S3-bucket

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      # Runs a set of commands using the runners shell
      - name: Deploy Website via a multi-line script
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: us-west-2
          
        run: |
          echo Hey I started a deployment
        
          aws s3api create-bucket --bucket super-test-XxX1234 --region us-west-2
          aws s3 cp index.html s3://super-test-XxX1234/index.html --acl public-read
          aws website s3://super-test-XxX1234/ --index-document index.html
            
          
